# Generated by Django 2.1.7 on 2019-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190613_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
