# Generated by Django 2.1.7 on 2019-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
