# Generated by Django 2.1.7 on 2019-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_user_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_varified_to_be_course_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
