# Generated by Django 2.1.7 on 2019-06-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20190615_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_varified_to_be_course_creator',
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
