# Generated by Django 2.1.7 on 2019-06-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20190621_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='belong_to_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Lesson'),
        ),
    ]
