# Generated by Django 2.1.7 on 2019-06-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_chat_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='name',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='chat',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Course'),
        ),
    ]
