# Generated by Django 2.1.7 on 2019-06-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20190629_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passedquiz',
            name='question_answer_result_pair',
        ),
        migrations.RemoveField(
            model_name='passedquiz',
            name='quiz_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='variant_result_pair',
        ),
        migrations.RemoveField(
            model_name='questionanswerresult',
            name='result',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='passedquiz',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedquiz',
            name='quiz_passed_username',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedquiz',
            name='username',
            field=models.CharField(default='no title yet', max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='belong_to_quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswerresult',
            name='belong_to_quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.PassedQuiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswerresult',
            name='correctanswer',
            field=models.CharField(default='no question yet', max_length=64),
        ),
        migrations.AddField(
            model_name='variantresult',
            name='belong_to_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
            preserve_default=False,
        ),
    ]
