# Generated by Django 2.1.7 on 2019-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_auto_20190629_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passedquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='passedquiz',
            name='quiz_passed_username',
        ),
        migrations.RemoveField(
            model_name='passedquiz',
            name='username',
        ),
        migrations.RemoveField(
            model_name='question',
            name='belong_to_quiz',
        ),
        migrations.RemoveField(
            model_name='questionanswerresult',
            name='belong_to_quiz',
        ),
        migrations.RemoveField(
            model_name='questionanswerresult',
            name='correctanswer',
        ),
        migrations.RemoveField(
            model_name='variantresult',
            name='belong_to_question',
        ),
        migrations.AddField(
            model_name='passedquiz',
            name='question_answer_result_pair',
            field=models.ManyToManyField(blank=True, related_name='question_answer_result', to='quiz.QuestionAnswerResult'),
        ),
        migrations.AddField(
            model_name='passedquiz',
            name='quiz_name',
            field=models.CharField(default='no name yet', max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='variant_result_pair',
            field=models.ManyToManyField(blank=True, related_name='posts', to='quiz.VariantResult'),
        ),
        migrations.AddField(
            model_name='questionanswerresult',
            name='result',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='posts', to='quiz.Question'),
        ),
    ]
