# Generated by Django 2.1.7 on 2019-06-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20190629_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedQuizzz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='no title yet', max_length=64)),
                ('quiz_passed_username', models.CharField(default=None, max_length=64)),
                ('quiz', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
        migrations.RemoveField(
            model_name='passedquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='passedquiz',
            name='quiz_passed_username',
        ),
        migrations.RemoveField(
            model_name='passedquiz',
            name='username',
        ),
        migrations.AddField(
            model_name='passedquiz',
            name='question_answer_result_pair',
            field=models.ManyToManyField(blank=True, related_name='question_answer_result', to='quiz.QuestionAnswerResult'),
        ),
        migrations.AddField(
            model_name='passedquiz',
            name='quiz_name',
            field=models.CharField(default='no name yet', max_length=64),
        ),
        migrations.AlterField(
            model_name='questionanswerresult',
            name='belong_to_quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.PassedQuizzz'),
        ),
    ]
