# Generated by Django 2.1.7 on 2019-06-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20190629_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='belong_to_quiz',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
