# Generated by Django 2.1.7 on 2019-06-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20190629_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='belong_to_quiz',
        ),
    ]
