# Generated by Django 2.1.7 on 2019-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_remove_question_belong_to_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passedquizzz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='questionanswerresult',
            name='belong_to_quiz',
        ),
        migrations.RemoveField(
            model_name='questionanswerresult',
            name='correctanswer',
        ),
        migrations.RemoveField(
            model_name='variantresult',
            name='belong_to_question',
        ),
        migrations.AddField(
            model_name='question',
            name='variant_result_pair',
            field=models.ManyToManyField(blank=True, related_name='posts', to='quiz.VariantResult'),
        ),
        migrations.AddField(
            model_name='questionanswerresult',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='posts', to='quiz.Question'),
        ),
        migrations.DeleteModel(
            name='PassedQuizzz',
        ),
    ]
