# Generated by Django 2.1.7 on 2019-06-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20190629_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedTestQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_passed_username', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title yet', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionVariantResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_choice', models.CharField(default='no title yet', max_length=64)),
                ('correct_choice', models.CharField(default='no title yet', max_length=64)),
                ('belong_to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.TestQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title yet', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='testquestion',
            name='belong_to_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.TestQuiz'),
        ),
        migrations.AddField(
            model_name='passedtestquiz',
            name='test_quiz_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.TestQuiz'),
        ),
    ]
