# Generated by Django 2.1.7 on 2019-06-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_auto_20190629_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswerresult',
            name='result',
        ),
        migrations.AddField(
            model_name='questionanswerresult',
            name='belong_to_quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.PassedTestQuiz'),
        ),
        migrations.AddField(
            model_name='questionanswerresult',
            name='correctanswer',
            field=models.CharField(default='no question yet', max_length=64),
        ),
    ]
