# Generated by Django 2.1.7 on 2019-06-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_testquiz_belong_to_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquiz',
            name='quiz_in_json',
            field=models.CharField(default='no title yet', max_length=1024),
        ),
    ]
