# Generated by Django 2.1.7 on 2019-06-29 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_testquiz_quiz_in_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passedtestquiz',
            old_name='test_quiz_name',
            new_name='test_quiz',
        ),
        migrations.AddField(
            model_name='passedtestquiz',
            name='test_quiz_pass_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passedtestquiz',
            name='test_quiz_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.User'),
        ),
        migrations.RemoveField(
            model_name='passedtestquiz',
            name='quiz_passed_username',
        ),
        migrations.AlterUniqueTogether(
            name='passedtestquiz',
            unique_together={('test_quiz', 'test_quiz_user', 'test_quiz_pass_attempt')},
        ),
    ]
