# Generated by Django 2.1.7 on 2019-06-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_auto_20190629_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswerresult',
            name='correctanswer',
        ),
    ]
